### ISSUE TITLE
Update TimeSketch and Plaso w/Python3 dependancies

### ISSUE THREAD

**Issue by orlikoski** [orlikoski/skadi_timesketch#2]
Based on https://github.com/log2timeline/plaso/issues/2398

**Comment by joachimmetz** [comment]
The more structural way to solve this is to use 1 package manager. So there are no cross-package manager conflicts such as the one causing this issue.

**Comment by orlikoski** [comment]
Thank you for your feedback. Skadi is deployed in multiple formats and a package manager doesn't make sense for them all.

This conflict is currently due to the recent upgrade of Plaso to Python 3 and how it breaks the documented method of installation on the TimeSketch website.  Everyone who used the APT package manager for Plaso found that the timesketch output for psorty.py no longer worked.  There was no warning in either Plaso or TimeSketch that this would happen.

Therefore I'll update my tooling as required as literally everyone who runs an update using APT with default settings will suffer from this loss until they install the python3 version of timesketch (which is  undocumented)

**Comment by joachimmetz** [comment]
> Skadi is deployed in multiple formats and a package manager doesn't make sense for them all.

You use several package managers to install your dependencies. Package managers that are known to not necessarily work together well.

> There was no warning in either Plaso or TimeSketch that this would happen.

This is limited to Xenial only, due to Xenial updating the Python shebang. There is no warning in Xenial either that this would happen, nor is it clear if this is documented (this is very likely hidden somewhere in the documentation).

What should be documented in your perspective? That if you're running plaso as python3 then to install python3 version of Timesketch not a python2 version to enable the plugin?

**Comment by orlikoski** [comment]
Here is why it is a large issue for end users. From that perspective this latest Plaso update resulted in a loss of functionality for all existing TimeSketch installations.  It disabled the timesketch output from Plaso on existing installations with no clear evidence for a reason behind that loss.

The Skadi project makes hard to setup, disparate DFIR tools easy to use and configure them, with documentation, to have an end to end data/work flow so that anyone can learn to collect, process, and analyse DFIR data.  It does that by using various methods as there is no control over the package manager, or lack thereof, used by those various tools in that tool stack. The resulting work is packaged into a turnkey DFIR solution as a digitally signed installer, as an OVA, and as a Vagrant box. This allows users to deploy in a way that suits their needs and is easiest for them.

I write and maintain my FOSS tools to be used by those who do not have a sysadmin background. It's primarily meant for overworked, underfunded IT security people and students trying to learn DFIR.  

This sort of issue stops Plaso from working with TimeSketch after doing nothing more than an update command.  There is nothing that can be easily found for why so it leaves novices stuck. 

Thank you for all of the work you've done to help the community with your FOSS contributions and this will be the last I respond to this.

**Comment by joachimmetz** [comment]
> Here is why it is a large issue for end users.

Unfortunately we don't control all the factors. Many issues are caused due to small local system configuration differences and take time and round-trips to troubleshoot. Also things continuously change, especially with an upcoming Python 2 deprecation deadline. IMHO the best way to account for change is to catch this with CI tests before deployment.

> This allows users to deploy in a way that suits their needs and is easiest for them.

Yes containerization takes away some of the challenges, but then puts the greater responsibility and burden on the maintainer. This makes the maintainer is dependent on upstream for changes and fixes, and upstream dependent on the maintainer to let them know about platforms and use-cases they support and issues they encounter. Open and clear communication between maintainer and upstream is a key part here.

> and this will be the last I respond to this.

This is unfortunate. I suggested discussing getting a structural solution in place, not a fix that only addresses the problem at hand and potentially breaks due to (un)foreseeable changes in the future. For this more discussion on this topic is needed.

As I've indicated before, work is in progress to get Timesketch onto GIFT PPA. This provides a dev track so some issues can be automatically tested. I'm happy to discuss getting a solution in place that helps catch the majority of issues during development and testing.
